/*
 * Copyright 2010-2021 JetBrains s.r.o. and Kotlin Programming Language contributors.
 * Use of this source code is governed by the Apache 2.0 license that can be found in the license/LICENSE.txt file.
 */

package org.jetbrains.kotlin.analysis.api.descriptors.test.components;

import com.intellij.testFramework.TestDataPath;
import org.jetbrains.kotlin.test.util.KtTestUtil;
import org.jetbrains.kotlin.test.TestMetadata;
import org.junit.jupiter.api.Nested;
import org.junit.jupiter.api.Test;

import java.io.File;
import java.util.regex.Pattern;

/** This class is generated by {@link GenerateNewCompilerTests.kt}. DO NOT MODIFY MANUALLY */
@SuppressWarnings("all")
@TestMetadata("analysis/analysis-api/testData/components/returnTargetSymbol")
@TestDataPath("$PROJECT_ROOT")
public class KtFe10ReturnTargetSymbolTestGenerated extends AbstractKtFe10ReturnTargetSymbolTest {
    @Test
    public void testAllFilesPresentInReturnTargetSymbol() throws Exception {
        KtTestUtil.assertAllTestsPresentByMetadataWithExcluded(this.getClass(), new File("analysis/analysis-api/testData/components/returnTargetSymbol"), Pattern.compile("^(.+)\\.kt$"), null, true);
    }

    @Test
    @TestMetadata("labeledReturn.kt")
    public void testLabeledReturn() throws Exception {
        runTest("analysis/analysis-api/testData/components/returnTargetSymbol/labeledReturn.kt");
    }

    @Test
    @TestMetadata("nomralReturn.kt")
    public void testNomralReturn() throws Exception {
        runTest("analysis/analysis-api/testData/components/returnTargetSymbol/nomralReturn.kt");
    }

    @Test
    @TestMetadata("unresolvedReturn.kt")
    public void testUnresolvedReturn() throws Exception {
        runTest("analysis/analysis-api/testData/components/returnTargetSymbol/unresolvedReturn.kt");
    }
}
